### ISSUE TITLE
jupyter-forward hangs and doesn't ask for token

### ISSUE THREAD

**Issue by jessecusack** [NCAR/jupyter-forward#108]
Previously this would work:

```
jupyter-forward --port=8892 --launch-command="qsub -l select=1:ncpus=1:mpiprocs=1 -l walltime=04:00:00 -q regular -A URTG0022" [username]@cheyenne.ucar.edu
```

But now I am not even prompted for a token response. I am not sure why this would change from one day to the next.

**Comment by andersy005** [comment]
🤔 That's strange... I was able to use the exact command and things seem to be working on my end. Which version of `jupyter-forward` are you running?

```bash
$ jupyter-forward --version
Jupyter Forward CLI Version: 2021.8.17
```

**Comment by jessecusack** [comment]
I also have version 2021.8.17. 

The good news is that as mysteriously as it stopped working, it now works again. I'll close this issue for now, but let you if it happens again.

**Comment by andersy005** [comment]
Glad to hear that the issue was _mysteriously_ resolved :). Yeah, feel free to reopen this issue when you encounter this in the future.
