### ISSUE TITLE
Better default port options

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/jupyter-forward#16]
Two related thoughts here:

1. We should let users specify `local_port` and `remote_port` separately
1. The default for `remote_port` should be `None`, which should indicate "just use whatever port `jupyter` returns" (i.e. 8888, or 8889 if 8888 is in use, or 8890, or ...)

I don't have strong opinions on the default for `local_port`. The two options that make the most sense are "use whatever `remote_port` turns out to be" or "use 8888". I'm leaning more towards the former, but am willing to be persuaded otherwise.

**Comment by andersy005** [comment]
Closing this as it's been addressed.
