### ISSUE TITLE
cheyenne login node use policies

### ISSUE THREAD

**Issue by klindsay28** [NCAR/jupyter-forward#20]
Based on the README, it sounds like the command `jupyter-forward start cheyenne` launches jupyter lab on a cheyenne login node. This differs from the `jlab-ch` and `jlab-dav` scripts provided by [ncar-python-tutorial](https://github.com/NCAR/ncar-python-tutorial), which ran jupyter lab within a batch job (PBS on cheyenne, SLURM on casper).

The [cheyenne use policies](https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/cheyenne-use-policies) state that cheyenne login nodes are for 'short, non-memory-intensive processes', such as 'text editing or running small serial scripts or programs'. In my experience, I find that jupyter lab can easily end up using substantial resources, particularly memory. This is even the case when farming out computations to dask clients, I think from jupyter lab's management of the work (e.g., the task graph can be huge). It seems like `jupyter-forward` is setting up users to use cheyenne login nodes in a way that can lead to violating the use policies, which will get the users in hot water with CISL.

Do you have plans for `jupyter-forward` to support running jupyter lab within a batch job launched from `HOST`, instead of running directly on `HOST`?

**Comment by kmpaul** [comment]
@klindsay28:  Thanks for bringing this up.  I think you make an excellent point.  I don't think we should *prevent* people from running on the login nodes, but we should caution people.  I've asked our sysadmins about running Jupyter sessions on the login nodes and they have said they are not terribly concerned about it.  They tell me that they have scripts to kill jobs that "hog" resources, which would certainly kill any Jupyter Lab sessions created by Jupyter Forward that got "expensive."  

Now, that said, I agree with you that we don't want to set up users to get in trouble with CISL sysadmins for excessive overuse of the login nodes.  So, to that end, I *do* think we should support launching the Jupyter Lab on the compute nodes.  I have an idea that I've sketched in #21.
