### ISSUE TITLE
Capture abort signal, and kill remote jupyter lab process

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/jupyter-forward#5]
When the user `^C`s out of the script, the `jupyter-lab` process (`jlab_exe` in #4) should be killed. On the telecon I believe we discussed a command-line argument that would let this process persist, but the default should definitely be to kill it.

**Comment by andersy005** [comment]
I addressed this issue in #9, and things seem to be working fine. When you get a chance, please give it a try and let me know how it goes.

**Comment by andersy005** [comment]
Closing this as it's been addressed in #9.
