### ISSUE TITLE
"source activate" instead of "conda activate"?

### ISSUE THREAD

**Issue by rsignell-usgs** [NCAR/jupyter-forward#80]
I just tried using jupyter-forward on our USGS HPC systems for the first time, and it failed because our sys admins recommend not using `conda activate`.   I guess `conda activate` loads the default environment, which then puts binaries in the path that are problematic for some use cases.  

I was able to get it working on our system by replacing the two instances of `conda activate` with `source activate` in `core.py`.   
Could we just make that change in main?

I guess the downside would be that specifying the `--conda-env` environment would then be required?

**Comment by andersy005** [comment]
>  I guess conda activate loads the default environment, which then puts binaries in the path that are problematic for some use cases.

I actually thought the switch to `conda activate` was motivated by the fact that `source activate` was corrupting `PATH`. From the docs, regarding the release of [conda version 4.4.0](https://docs.conda.io/projects/conda/en/latest/release-notes.html#recommended-change-to-enable-conda-in-your-shell): 

> conda activate: The logic and mechanisms underlying environment activation have been reworked. With conda 4.4, conda activate and conda deactivate are now the preferred commands for activating and deactivating environments. You'll find they are much more snappy than the source activate and source deactivate commands from previous conda versions. The conda activate command also has advantages of (1) being universal across all OSes, shells, and platforms, and (2) not having path collisions with scripts from other packages like Python virtualenv's activate script.


> I was able to get it working on our system by replacing the two instances of conda activate with source activate in core.py.
Could we just make that change in main?

> I guess the downside would be that specifying the --conda-env environment would then be required?

I think we could add a flag/option (`use_conda_activate`) to the `Runner` class to enable or disable conda activate/source activate. We could make `conda activate` the default option, and then the user would have to opt-out (in this case, we would replace `conda activate` with `source activate`). I am imagining something along these lines 

```bash 
jupyter-forward --use-conda-activate ... 
```

We may be able to iron out some of the other issues you pointed out in a PR. Would you be interested in submitting a PR when you get a moment ;)?

**Comment by ocefpaf** [comment]
@andersy005 you are right and `conda activate` is recommended. However, that is designed for end user. Under the hood it will call source activate for you by figuring out the shell and OS you are in. Because `jupyter-forward` will always be called from a Linux server I would use `source activate` instead to avoid the issues @rsignell-usgs is having and to make it a bit simpler.

**Comment by andersy005** [comment]
Thank you for the clarification, @ocefpaf!

**Comment by malmans2** [comment]
I tried the latest version and it looks like `source activate` doesn't work with `csh` shells?
Maybe it's because my conda is not set up correctly? From my `.cshrc`:
```
# Anaconda
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if ( -f "/noc/msm/scratch/climate/malmans/mambaforge/etc/profile.d/conda.csh" ) then
    source "/noc/msm/scratch/climate/malmans/mambaforge/etc/profile.d/conda.csh"
else
    setenv PATH "/noc/msm/scratch/climate/malmans/mambaforge/bin:$PATH"
endif
# <<< conda initialize <<<
```
Does it make sense to add a flag to choose `source/conda activate`, or maybe a `try/except`?

**Comment by andersy005** [comment]
> Does it make sense to add a flag to choose source/conda activate, or maybe a try/except?

@malmans2, 👍🏽 It's reasonable to have a `try except` block. In the meantime, do you run into an issue when using the `--shell` option and it is set to `/usr/bin/csh -l` i.e.

```bash
jupyter-forward --shell "/usr/bin/csh -l" .... 
```

???

**Comment by malmans2** [comment]
Yes, that doesn't fix it. `source activate` doesn't work on `csh`. I.e., if I do `source activate env` from terminal I get:
```
activate: No such file or directory.
```

**Comment by andersy005** [comment]
> Yes, that doesn't fix it. `source activate` doesn't work on `csh`. I.e., if I do `source activate env` from terminal I get:
> 
> ```
> activate: No such file or directory.
> ```



I added the `try except ...` block in #94. Could you give it a try to confirm that the `conda activate` issue is addressed?

**Comment by malmans2** [comment]
Almost, but I now get stuck here:
```
****************************************************************************************** Launching Jupyter Lab ******************************************************************************************
sh -l -c "source activate jupyter && jupyter lab --no-browser --ip=\$(hostname -f) >& $HOME/.jupyter_forward/log.2021-07-06T16-12-32"
```

I think the `try/except` block should record whether `conda/source` has been used, so the same command can be used later.

However, I get stuck even if I change `source` with `conda` [here](https://github.com/NCAR/jupyter-forward/blob/61062ce6afb440efd079e150e296a853d19e890e/jupyter_forward/core.py#L197-L198), I think because the command doesn't work with `csh` (I also tried `--shell "/usr/bin/csh -l"` but that doesn't work either).

**Comment by andersy005** [comment]
Good catch! Fixed it in the latest commit.
